### ISSUE TITLE
creating graphs out of images 

### ISSUE THREAD

**Issue by ZeinabRahbar** [double125/Graph-Matching-Attention#3]
hi dear author in phase when i want to create graph out of data of trainval36 with code preprocess images .py i do not know why i get an error that there is nulls in my file trainval and it be stopped i had to change decdestring to decodebyte since python after 3.1 does not support it.

**Comment by ZeinabRahbar** [comment]
13945it [06:30, 35.75it/s]
Traceback (most recent call last):
  File "preprocess_image.py", line 156, in <module>
    features_to_zarr(phase)
  File "preprocess_image.py", line 79, in features_to_zarr
    for item in tqdm(reader):   
  File "/home/hoopad/.local/lib/python3.8/site-packages/tqdm/std.py", line 1182, in __iter__
    for obj in iterable:
  File "/usr/lib/python3.8/csv.py", line 111, in __next__
    row = next(self.reader)
_csv.Error: line contains NUL
it is errror which i get running the script
